# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Miles Koller
tagline:             'Blog'
description:         'Blog of Miles Koller'
url:                 http://mileskoller.me/blog
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Miles Koller
  url:               https://twitter.com/mileskoller
  email:             mileskoller@gmail.com

# Custom vars
version:             1.0.0
